apiVersion: v1
kind: ConfigMap
metadata:
  name: apikey-usage-inspector-config
  namespace: default
data:
  # Prometheus Push Gateway configuration
  PUSH_GATEWAY_ENABLED: "true"
  PUSH_GATEWAY_URL: "http://prometheus-pushgateway:9091"
  PUSH_GATEWAY_JOB: "cron-apikey-usage"
  
  # DNS mapping for bypassing CloudFlare
  DNS_MAP: '{"multichain-api.birdeye.so": "37.59.30.17"}'
  
  # FlareResolver configuration (if needed)
  FLARESOLVER_ENABLED: "false"
  FLARESOLVER_ENDPOINT: "http://flaresolverr:8191/v1"
  
  # Debug settings
  DEBUG_ENABLED: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: apikey-usage-inspector-secrets
  namespace: default
type: Opaque
stringData:
  # Add your API keys here
  BIRDEYE_API_KEY: "your-birdeye-api-key"
  QUICKNODE_API_KEY: "your-quicknode-api-key"
  # Add any other sensitive configuration
