apiVersion: batch/v1
kind: CronJob
metadata:
  name: apikey-usage-inspector
  namespace: default
  labels:
    app: apikey-usage-inspector
spec:
  # Run every 12 hours at minute 0 (12:00 AM and 12:00 PM)
  schedule: "0 */12 * * *"
  
  # Keep last 3 successful jobs and 1 failed job for debugging
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  
  # Don't allow concurrent executions
  concurrencyPolicy: Forbid
  
  # Job will be considered failed if it takes more than 10 minutes
  activeDeadlineSeconds: 600
  
  jobTemplate:
    spec:
      # Don't retry failed jobs automatically
      backoffLimit: 0
      
      # Clean up completed jobs after 1 hour
      ttlSecondsAfterFinished: 3600
      
      template:
        metadata:
          labels:
            app: apikey-usage-inspector
        spec:
          restartPolicy: Never
          
          containers:
          - name: apikey-usage-inspector
            image: apikey-usage-inspector:latest
            imagePullPolicy: IfNotPresent
            
            # Resource limits to prevent resource hogging
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
            
            # Environment variables from ConfigMap
            envFrom:
            - configMapRef:
                name: apikey-usage-inspector-config
            - secretRef:
                name: apikey-usage-inspector-secrets
            
            # Security context
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                - ALL
          
          # Security context for the pod
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
