apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yaml
  - configmap.yaml

# example

# resources:
# - github.com/jinbangyi/apikey-usage-inspector/k8s?ref=develop

# patches:
# - target:
#     kind: ConfigMap
#   patch: |-
#     - op: replace
#       path: /data
#       value: 
#         PUSH_GATEWAY_URL: "http://prometheus-pushgateway-prod.devops:9091"
#         PUSH_GATEWAY_ENABLED: "true"
#         BIRDEYE_ENABLED: "false"
# - target:
#     kind: Secret
#   patch: |-
#     - op: replace
#       path: /stringData
#       value: 
#         QUICKNODE_CONSOLE_APIKEY: "xx"
# - target:
#     kind: CronJob
#   patch: |-
#     - op: replace
#       path: /spec/jobTemplate/spec/template/spec/containers/0/image
#       value: 
#         jinbangyi/apikey-usage-inspector:0.0.1

